source 'https://api.berkshelf.com'

cookbook 'build-essential'
cookbook 'git'
cookbook 'imagemagick'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'ruby_build'
cookbook 'rbenv', github: 'fnichol/chef-rbenv'
cookbook 'simple_iptables', github: 'dcrosta/cookbook-simple-iptables'
cookbook 'xml'
